### ISSUE TITLE
GPL?

### ISSUE THREAD

**Issue by avocadoras** [orzechowskid/flymake-eslint#14]
Would like to know why the package is released under MIT?

**Comment by orzechowskid** [comment]
no reason except it is the license with which I have the most familiarity; I have previously released, and contributed to, projects licensed under MIT.

I'm wondering now, is the license preventing you from using this library?  Or am I potentially in violation of something?

**Comment by avocadoras** [comment]
IANAL, but Emacs is released under GPL, and I believe any derivative works should be also released under the same license. Derivative works is broad but may apply in this case. Again, am not a lawyer. 

Either way, not sure why go MIT when Emacs is GPL.

**Comment by alexanderbarbosa** [comment]
@avocadoras 
Emacs' packages are not part of Emacs itself so those are not obliged to use GPL.
