### ISSUE TITLE
Melpa?

### ISSUE THREAD

**Issue by eabarbosa** [orzechowskid/flymake-eslint#4]
Could you provide your package on melpa.org? 

Thanks!

**Comment by orzechowskid** [comment]
I cleaned it up a bit and opened a PR to get it into MELPA:  https://github.com/melpa/melpa/pull/6103

thank you for the encouragement!

**Comment by orzechowskid** [comment]
just to follow up, that MELPA PR has been accepted and flymake-eslint is now available by running the command `M-x package-install [RET] flymake-eslint [RET]`.

**Comment by alexanderbarbosa** [comment]
@orzechowskid 
Just did that yesterday... THANKS!
